micronaut:
  application:
    name: proxynaut-example
  security:
    enabled: true
    authentication: bearer

# This silly config will enable proxying http://localhost:8080/proxy/page1 to /page1

proxynaut:
  proxies:
      #  http://localhost:8080/proxy/page1 -> SECURE
    - context: /proxy
      uri: http://localhost:8080
      qualifier: "secureProxy"
      invoke-using-method: "secured"
      allowed-methods: ["GET"]
      timeoutMs: 20000
      #  http://localhost:8080/proxy/another/page1 -> UNSECURE
    - context: /proxy/another
      uri: http://localhost:8080
      qualifier: "unsecureProxy"
      invoke-using-method: "unsecured"
      allowed-methods: ["GET"]
      include-request-headers: [ "X-OUT-HEADER" ]
      include-response-headers: [ "X-RETURN-HEADER" ]
      include-request-cookies: [ "outCookie" ]
      include-response-cookies: [ "returnCookie" ]
      timeoutMs: 20000
      #  http://localhost:8080/defaultproxy/page1 -> SECURE
    - context: /defaultproxy
      uri: http://localhost:8080
      allowed-methods: [ "GET" ]

server:
  port: 8080
